#ifndef CHATCONST_H
#define CHATCONST_H
#include <QColor>
namespace Smiles{
	const int Num_Smiles= 40; 
	const QString smiles[Num_Smiles][2]={
		{"(S)","<img src=\":/Smiles/afraid.png\" width=\"24\" height=\"24\" />"},
		{"(L)","<img src=\":/Smiles/amorous.png\" width=\"24\" height=\"24\" />"},
		{"(A)","<img src=\":/Smiles/angel.png\" width=\"24\" height=\"24\" />"},
		{"8o|","<img src=\":/Smiles/angry.png\" width=\"24\" height=\"24\" />"},
		{"|(","<img src=\":/Smiles/arrogant.png\" width=\"24\" height=\"24\" />"},
		{"(U)","<img src=\":/Smiles/beat-up.png\" width=\"24\" height=\"24\" />"},
		{"(B)","<img src=\":/Smiles/bomb.png\" width=\"24\" height=\"24\" />"},
		{"o_0","<img src=\":/Smiles/bulgy-eyes.png\" width=\"24\" height=\"24\" />"},
		{"(O)","<img src=\":/Smiles/clock.png\" width=\"24\" height=\"24\" />"},
		{":S","<img src=\":/Smiles/confused.png\" width=\"24\" height=\"24\" />"},
		{":'(","<img src=\":/Smiles/crying.png\" width=\"24\" height=\"24\" />"},
		{"(N)","<img src=\":/Smiles/curse.png\" width=\"24\" height=\"24\" />"},
		{"(6)","<img src=\":/Smiles/devil.png\" width=\"24\" height=\"24\" />"},
		{":#","<img src=\":/Smiles/disappointed.png\" width=\"24\" height=\"24\" />"},
		{":^)","<img src=\":/Smiles/dont-know.png\" width=\"24\" height=\"24\" />"},
		{":$","<img src=\":/Smiles/embarrassed.png\" width=\"24\" height=\"24\" />"},
		{":D","<img src=\":/Smiles/excited.png\" width=\"24\" height=\"24\" />"},
		{"*)","<img src=\":/Smiles/eyeroll.png\" width=\"24\" height=\"24\" />"},
		{"(V)","<img src=\":/Smiles/fingers-crossed.png\" width=\"24\" height=\"24\" />"},
		{":!","<img src=\":/Smiles/foot-in-mouth.png\" width=\"24\" height=\"24\" />"},
		{"(G)","<img src=\":/Smiles/freaked-out.png\" width=\"24\" height=\"24\" />"},
		{"8)","<img src=\":/Smiles/glasses-cool.png\" width=\"24\" height=\"24\" />"},
		{":)","<img src=\":/Smiles/happy.png\" width=\"24\" height=\"24\" />"},
		{"-.-\"","<img src=\":/Smiles/hot.png\" width=\"24\" height=\"24\" />"},
		{"<3","<img src=\":/Smiles/in_love.png\" width=\"24\" height=\"24\" />"},
		{":*","<img src=\":/Smiles/kiss.png\" width=\"24\" height=\"24\" />"},
		{"L:)","<img src=\":/Smiles/loser.png\" width=\"24\" height=\"24\" />"},
		{":|","<img src=\":/Smiles/neutral.png\" width=\"24\" height=\"24\" />"},
		{":@","<img src=\":/Smiles/pissed-off.png\" width=\"24\" height=\"24\" />"},
		{"?:(","<img src=\":/Smiles/question.png\" width=\"24\" height=\"24\" />"},
		{":(","<img src=\":/Smiles/sad.png\" width=\"24\" height=\"24\" />"},
		{"^o)","<img src=\":/Smiles/sarcastic.png\" width=\"24\" height=\"24\" />"},
		{":O","<img src=\":/Smiles/shocked.png\" width=\"24\" height=\"24\" />"},
		{":X","<img src=\":/Smiles/shut-mouth.png\" width=\"24\" height=\"24\" />"},
		{"+o(","<img src=\":/Smiles/sick.png\" width=\"24\" height=\"24\" />"},
		{"Z:)","<img src=\":/Smiles/sleeping.png\" width=\"24\" height=\"24\" />"},
		{":P","<img src=\":/Smiles/tongue.png\" width=\"24\" height=\"24\" />"},
		{":[","<img src=\":/Smiles/vampire.png\" width=\"24\" height=\"24\" />"},
		{"XD","<img src=\":/Smiles/XD.png\" width=\"24\" height=\"24\" />"},
		{";)","<img src=\":/Smiles/wink.png\" width=\"24\" height=\"24\" />"}
	};
	const QString smiles_paths[Num_Smiles]={
		":/Smiles/afraid.png",
		":/Smiles/amorous.png",
		":/Smiles/angel.png" ,
		":/Smiles/angry.png",
		":/Smiles/arrogant.png",
		":/Smiles/beat-up.png",
		":/Smiles/bomb.png",
		":/Smiles/bulgy-eyes.png",
		":/Smiles/clock.png",
		":/Smiles/confused.png",
		":/Smiles/crying.png",
		":/Smiles/curse.png",
		":/Smiles/devil.png",
		":/Smiles/disappointed.png",
		":/Smiles/dont-know.png",
		":/Smiles/embarrassed.png",
		":/Smiles/excited.png",
		":/Smiles/eyeroll.png",
		":/Smiles/fingers-crossed.png",
		":/Smiles/foot-in-mouth.png",
		":/Smiles/freaked-out.png",
		":/Smiles/glasses-cool.png",
		":/Smiles/happy.png",
		":/Smiles/hot.png",
		":/Smiles/in_love.png",
		":/Smiles/kiss.png",
		":/Smiles/loser.png",
		":/Smiles/neutral.png",
		":/Smiles/pissed-off.png",
		":/Smiles/question.png",
		":/Smiles/sad.png",
		":/Smiles/sarcastic.png",
		":/Smiles/shocked.png",
		":/Smiles/shut-mouth.png",
		":/Smiles/sick.png",
		":/Smiles/sleeping.png",
		":/Smiles/tongue.png",
		":/Smiles/vampire.png",
		":/Smiles/XD.png",
		":/Smiles/wink.png"
	};
}
namespace Colors{
	const QColor ServerColor("#FF8000");
}
#endif